sound_map = {
    -1: "sounds/Bathyspherics Effects.wav",
    1: "sounds/Anemone High Violin.wav",
    2: "sounds/Jingle Shells Piccolo.wav",
    3: "sounds/Blood Seat Star High Trumpet.wav",
    4: "sounds/Jingle Shells Piccolo.wav",
    5: "sounds/Anemone High Violin.wav",
    6: "sounds/Hydroids High Cello.wav",
    7: "sounds/Jingle Shells Piccolo.wav",
    8: "sounds/Anemone High Violin.wav",
    9: "sounds/Blood Seat Star High Trumpet.wav",
    10: "sounds/Jingle Shells Piccolo.wav",
    11: "sounds/Crumb of Bread Sponge Horn.wav",
    12: "sounds/Hydroids Middle Cello.wav",
    13: "sounds/Crumb of Bread Sponge Horn.wav",
    14: "sounds/Crumb of Bread Sponge Horn.wav",
    15: "sounds/Crumb of Bread Sponge Horn.wav",
    16: "sounds/Hydroids Middle Cello.wav",
    17: "sounds/Blood Sea Star Middle Trumpet.wav",
    18: "sounds/Crumb of Bread Sponge Horn.wav",
    19: "sounds/Crumb of Bread Sponge Horn.wav",
    20: "sounds/Sea Grapes Low Bassoon.wav",
    21: "sounds/Hydroids Low Cello.wav",
    22: "sounds/Hydroids Low Cello.wav",
    23: "sounds/Sea Grapes Low Bassoon.wav",
    24: "sounds/Sea Grapes Low Bassoon.wav",
    25: "sounds/Crumb of Bread Sponge Horn.wav",
    26: "sounds/Hydroids Low Cello.wav",
    27: "sounds/Sea Grapes Low Bassoon.wav"

}